#!/usr/bin/env python3
"""DeYoung Fleet Expansion GPU research report - body PDF (ReportLab).
Follows pdf skill report brief: cascade palette, TocDocTemplate+multiBuild,
Paragraph-wrapped tables, matplotlib charts per charts.md, callout boxes."""
import os, sys, hashlib

PDF_SKILL_DIR = "/home/z/my-project/skills/pdf"
sys.path.insert(0, os.path.join(PDF_SKILL_DIR, "scripts"))

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, PageBreak,
                                Table, TableStyle, Image, KeepTogether,
                                CondPageBreak, HRFlowable)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

FONT_DIR = "/usr/share/fonts"
pdfmetrics.registerFont(TTFont("NotoSerifSC", f"{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf"))
pdfmetrics.registerFont(TTFont("NotoSerifSC-Bold", f"{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf"))
# Sandbox has the variable-weight Noto Sans SC only; try it, skip cleanly if unreadable
_nsans = f"{FONT_DIR}/truetype/chinese/NotoSansSC[wght].ttf"
try:
    pdfmetrics.registerFont(TTFont("Noto Sans SC", _nsans))
    pdfmetrics.registerFont(TTFont("Noto Sans SC Bold", _nsans))
except Exception:
    pass  # fallback chain tolerates unregistered fonts; content is Latin-only
pdfmetrics.registerFont(TTFont("FreeSerif", f"{FONT_DIR}/truetype/freefont/FreeSerif.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-Bold", f"{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-Italic", f"{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-BoldItalic", f"{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf"))
pdfmetrics.registerFont(TTFont("DejaVuSans", f"{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf"))
registerFontFamily("NotoSerifSC", normal="NotoSerifSC", bold="NotoSerifSC-Bold")
registerFontFamily("Noto Sans SC", normal="Noto Sans SC", bold="Noto Sans SC Bold")
registerFontFamily("FreeSerif", normal="FreeSerif", bold="FreeSerif-Bold",
                   italic="FreeSerif-Italic", boldItalic="FreeSerif-BoldItalic")
registerFontFamily("DejaVuSans", normal="DejaVuSans", bold="DejaVuSans")

from pdf import install_font_fallback
install_font_fallback()

# ---- Cascade Palette (auto-generated by design_engine.py palette-cascade) ----
PAGE_BG       = colors.HexColor('#f2f2f0')
SECTION_BG    = colors.HexColor('#eeeeec')
CARD_BG       = colors.HexColor('#eeedea')
TABLE_STRIPE  = colors.HexColor('#efeeec')
HEADER_FILL   = colors.HexColor('#61573c')
COVER_BLOCK   = colors.HexColor('#776f57')
BORDER        = colors.HexColor('#bdb9ae')
ICON          = colors.HexColor('#7a6a3a')
ACCENT        = colors.HexColor('#866f2c')
ACCENT_2      = colors.HexColor('#4299b7')
TEXT_PRIMARY  = colors.HexColor('#1a1917')
TEXT_MUTED    = colors.HexColor('#908e87')
SEM_SUCCESS   = colors.HexColor('#4a9061')
SEM_WARNING   = colors.HexColor('#a98743')
SEM_ERROR     = colors.HexColor('#91433c')
SEM_INFO      = colors.HexColor('#406a94')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

MARGIN = 0.9 * inch
PAGE_W, PAGE_H = A4
AVAIL = PAGE_W - 2 * MARGIN
AVAIL_H = PAGE_H - 2 * MARGIN
H1_ORPHAN = AVAIL_H * 0.25
MAX_KEEP = PAGE_H * 0.4

OUT = "/home/z/my-project/research/body.pdf"
TITLE = "DeYoung Fleet Expansion: Free and Low-Cost Cloud GPU Research 2026"

# ---------- styles ----------
body_st = ParagraphStyle("Body", fontName="FreeSerif", fontSize=10.5, leading=17,
                         alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY, spaceAfter=10)
lead_st = ParagraphStyle("Lead", parent=body_st, fontSize=11, leading=18, textColor=TEXT_PRIMARY)
h1_st = ParagraphStyle("H1", fontName="FreeSerif", fontSize=22, leading=27,
                       textColor=TEXT_PRIMARY, spaceBefore=18, spaceAfter=4)
h2_st = ParagraphStyle("H2", fontName="FreeSerif", fontSize=15, leading=20,
                       textColor=HEADER_FILL, spaceBefore=14, spaceAfter=6)
h3_st = ParagraphStyle("H3", fontName="FreeSerif", fontSize=11.5, leading=16,
                       textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=5)
kicker_st = ParagraphStyle("Kicker", fontName="FreeSerif", fontSize=10, leading=14,
                           textColor=TEXT_MUTED, spaceAfter=2)
bullet_st = ParagraphStyle("Bullet", parent=body_st, leftIndent=16, bulletIndent=4,
                           spaceAfter=6, alignment=TA_LEFT)
quote_st = ParagraphStyle("Quote", fontName="FreeSerif-Italic", fontSize=10.5, leading=16,
                          leftIndent=24, textColor=TEXT_PRIMARY, spaceBefore=6, spaceAfter=10,
                          borderPadding=(4, 8, 4, 8))
caption_st = ParagraphStyle("Caption", fontName="FreeSerif", fontSize=8.5, leading=12,
                            alignment=TA_CENTER, textColor=TEXT_MUTED)
th_st = ParagraphStyle("TH", fontName="FreeSerif", fontSize=9.5, leading=13,
                       textColor=colors.white, alignment=TA_CENTER)
td_st = ParagraphStyle("TD", fontName="FreeSerif", fontSize=9, leading=12.5,
                       textColor=TEXT_PRIMARY, alignment=TA_LEFT)
tdc_st = ParagraphStyle("TDC", parent=td_st, alignment=TA_CENTER)
stat_st = ParagraphStyle("Stat", fontName="FreeSerif", fontSize=20, leading=24,
                         textColor=ACCENT, alignment=TA_CENTER)
statlb_st = ParagraphStyle("StatL", fontName="FreeSerif", fontSize=8.5, leading=11.5,
                           textColor=TEXT_MUTED, alignment=TA_CENTER)
bib_st = ParagraphStyle("Bib", fontName="FreeSerif", fontSize=9, leading=13.5,
                        leftIndent=24, firstLineIndent=-24, textColor=TEXT_PRIMARY,
                        spaceAfter=5, alignment=TA_LEFT)
toc0 = ParagraphStyle("TOC0", fontName="FreeSerif", fontSize=12, leading=20, leftIndent=6,
                      textColor=TEXT_PRIMARY)
toc1 = ParagraphStyle("TOC1", fontName="FreeSerif", fontSize=10.5, leading=16, leftIndent=26,
                      textColor=TEXT_PRIMARY)
toc_title_st = ParagraphStyle("TOCTitle", fontName="FreeSerif", fontSize=20, leading=26,
                              textColor=TEXT_PRIMARY, spaceAfter=14)

# ---------- doc template ----------
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, "bookmark_name"):
            level = getattr(flowable, "bookmark_level", 0)
            text = getattr(flowable, "bookmark_text", "")
            key = getattr(flowable, "bookmark_key", "")
            self.notify("TOCEntry", (level, text, self.page, key))

def on_page(canvas, doc):
    canvas.saveState()
    canvas.setFont("FreeSerif", 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 0.55 * inch, "DeYoung Fleet Expansion - GPU Infrastructure Research (2026)")
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 0.63 * inch, PAGE_W - MARGIN, PAGE_H - 0.63 * inch)
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
    canvas.setFillColor(TEXT_MUTED)
    canvas.setFont("FreeSerif", 7.5)
    canvas.drawString(MARGIN, 0.45 * inch, "DeYoung Ltd - Fleet Engineering")
    canvas.drawRightString(PAGE_W - MARGIN, 0.45 * inch, "Page %d" % doc.page)
    canvas.restoreState()

def add_heading(text, style, level=0):
    key = "h_%s" % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

def h1(story, text):
    story.append(CondPageBreak(H1_ORPHAN))
    hp = add_heading(text, h1_st, level=0)
    rule = HRFlowable(width="100%", color=ACCENT, thickness=1.4, spaceBefore=2, spaceAfter=12)
    story.append(KeepTogether([hp, rule]))

def h2(story, text, toc=False):
    story.append(CondPageBreak(H1_ORPHAN * 0.6))
    if toc:
        story.append(add_heading(text, h2_st, level=1))
    else:
        story.append(Paragraph("<b>%s</b>" % text, h2_st))

def P(story, text, style=None):
    story.append(Paragraph(text, style or body_st))

def B(story, text):
    story.append(Paragraph("<bullet>•</bullet> " + text, bullet_st))

def callout(story, stats):
    """stats: list of (big, label) tuples -> row of stat boxes."""
    cells, widths = [], []
    n = len(stats)
    w = min(150, (AVAIL * 0.96) / n - 12)
    for big, label in stats:
        inner = Table([[Paragraph("<b>%s</b>" % big, stat_st)],
                       [Paragraph(label, statlb_st)]], colWidths=[w])
        inner.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), CARD_BG),
            ("BOX", (0, 0), (-1, -1), 1, ACCENT),
            ("TOPPADDING", (0, 0), (-1, 0), 9),
            ("BOTTOMPADDING", (0, 1), (-1, 1), 9),
            ("TOPPADDING", (0, 1), (-1, 1), 1),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 1),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        cells.append(inner)
        widths.append(w + 12)
    row = Table([cells], colWidths=widths, hAlign="CENTER")
    row.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
    ]))
    story.append(Spacer(1, 8))
    story.append(KeepTogether(row))
    story.append(Spacer(1, 12))

def mk_table(story, headers, rows, ratios, caption, align_center_cols=()):
    data = [[Paragraph("<b>%s</b>" % h, th_st) for h in headers]]
    for r in rows:
        line = []
        for i, c in enumerate(r):
            st = tdc_st if i in align_center_cols else td_st
            line.append(Paragraph(c, st))
        data.append(line)
    total = sum(ratios)
    widths = [AVAIL * 0.97 * (x / total) for x in ratios]
    t = Table(data, colWidths=widths, hAlign="CENTER", repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        style.append(("BACKGROUND", (0, i), (-1, i),
                      TABLE_ROW_ODD if i % 2 else TABLE_ROW_EVEN))
    t.setStyle(TableStyle(style))
    story.append(Spacer(1, 14))
    story.append(t)
    story.append(Spacer(1, 6))
    story.append(Paragraph(caption, caption_st))
    story.append(Spacer(1, 14))

# ---------- charts ----------
def make_charts():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    plt.rcParams["font.sans-serif"] = ["DejaVu Sans"]
    plt.rcParams["axes.unicode_minus"] = False
    ACC = "#866f2c"; HDR = "#61573c"; MUT = "#908e87"; TXT = "#1a1917"

    # Chart 1: monthly free GPU hours per added account
    fig, ax = plt.subplots(figsize=(7.2, 3.0), constrained_layout=True)
    names = ["Kaggle (per existing account)", "Lightning AI (free tier, interruptible)",
             "Modal (Starter $30/mo credits)", "Azure for Students (amortized monthly)"]
    vals = [130, 80, 50, 12]
    cols = [HDR, ACC, ACC, ACC]
    y = range(len(names))[::-1]
    bars = ax.barh(list(y), vals, height=0.58, color=cols, edgecolor="none")
    for yi, v in zip(y, vals):
        ax.text(v + 2, yi, "%d h" % v, va="center", ha="left", fontsize=10, color=TXT)
    ax.set_yticks(list(y))
    ax.set_yticklabels(names, fontsize=9.5, color=TXT)
    ax.set_xlim(0, 150)
    ax.set_xlabel("Free GPU hours per month, per account", fontsize=9.5, color=MUT)
    for s in ("top", "right", "left"):
        ax.spines[s].set_visible(False)
    ax.spines["bottom"].set_color(MUT)
    ax.tick_params(colors=MUT, labelcolor=TXT)
    ax.grid(False)
    fig.savefig("/home/z/my-project/research/chart_capacity.png", dpi=200)
    plt.close(fig)

    # Chart 2: wall time for two concurrent 60s films vs effective fleet size
    fig, ax = plt.subplots(figsize=(7.2, 3.0), constrained_layout=True)
    fleet = ["3 workers", "6 workers (today)", "10 workers", "20 workers"]
    hours = [12.0, 6.0, 3.6, 1.8]
    cols2 = [HDR, HDR, ACC, ACC]
    y2 = range(len(fleet))[::-1]
    ax.barh(list(y2), hours, height=0.58, color=cols2, edgecolor="none")
    for yi, v in zip(y2, hours):
        ax.text(v + 0.25, yi, "%.1f h" % v, va="center", ha="left", fontsize=10, color=TXT)
    ax.set_yticks(list(y2))
    ax.set_yticklabels(fleet, fontsize=9.5, color=TXT)
    ax.set_xlim(0, 14)
    ax.set_xlabel("Hours until BOTH users' 60-second films are done", fontsize=9.5, color=MUT)
    for s in ("top", "right", "left"):
        ax.spines[s].set_visible(False)
    ax.spines["bottom"].set_color(MUT)
    ax.tick_params(colors=MUT, labelcolor=TXT)
    ax.grid(False)
    fig.savefig("/home/z/my-project/research/chart_walltime.png", dpi=200)
    plt.close(fig)

from PIL import Image as PILImage

def embed_image(path, max_width, max_height=None):
    if max_height is None:
        max_height = A4[1] * 0.35
    pil = PILImage.open(path)
    ow, oh = pil.size
    rw = max_width / ow if ow > max_width else 1.0
    rh = max_height / oh if oh > max_height else 1.0
    r = min(rw, rh)
    return Image(path, width=ow * r, height=oh * r)

def chart_block(story, png, caption):
    img = embed_image(png, AVAIL * 0.97)
    story.append(Spacer(1, 20))
    story.append(img)
    story.append(Spacer(1, 8))
    story.append(Paragraph(caption, caption_st))
    story.append(Spacer(1, 20))

# ================= CONTENT =================
make_charts()
story = []

# ---- TOC page ----
story.append(Paragraph("<b>Contents</b>", toc_title_st))
toc = TableOfContents()
toc.levelStyles = [toc0, toc1]
story.append(toc)
story.append(PageBreak())

# ---- Chapter 1 ----
h1(story, "Chapter 1 - Executive Summary")
P(story, "DeYoung's render fleet is a real, working production system: six Kaggle GPU accounts, "
 "coordinated by an always-on fleet brain, claiming render jobs straight out of the production "
 "Postgres queue and delivering finished scenes to the studio. The engineering works. What the "
 "platform has run out of is capacity: as of September 7-8, 2026, every one of the six accounts has "
 "burned its full weekly GPU allowance of 30 hours, the fleet is grounded until the weekly reset, "
 "and the owner's campaign film is queued behind that wall. This report answers the owner's direct "
 "question - which additional free or nearly-free cloud GPUs can join the fleet, verified against "
 "2026 reality rather than recycled marketing claims - and quantifies what each addition buys for "
 "the two-users-at-once scenario that keeps the owner up at night.", lead_st)
P(story, "Three providers passed a deliberately strict verification bar. <b>Modal</b> is the "
 "standout: a Starter plan with no base fee and no credit card that grants 30 dollars of compute "
 "credits every month, supports ten concurrent GPU containers, and exposes the cleanest "
 "programmatic interface of anything surveyed. <b>Lightning AI</b> offers roughly 80 GPU-hours per "
 "month on interruptible T4/A10 machines from its free Studio, also without a card. <b>Hugging "
 "Face</b> runs a community GPU grant program that costs nothing to apply for and would put A100 "
 "slices behind a public DeYoung Space if granted. One conditional candidate - <b>Azure for "
 "Students</b> - needs school verification the owner may or may not have. Everything else with a "
 "tempting landing page failed the bar for concrete, verified reasons: no official automation "
 "interface, no CUDA compatibility, or one-shot trial credits that cannot power a fleet.")
P(story, "The honest conclusion about scale: free tiers top out around ten to twelve sixty-second "
 "films per week no matter how many Kaggle-style accounts are stacked, because each account is a "
 "30-hour weekly tank, not an always-on machine. The 20-worker dream is reachable, but it is "
 "reached by adding two or three genuinely automatable free platforms now and letting the first "
 "three paying users fund interruptible RTX 4090 capacity at roughly 1.76 dollars per finished "
 "sixty-second film - which turns the 24-hour wait into a 2-to-4-hour delivery and leaves a "
 "45-70 percent GPU margin at the owner's planned prices.")
callout(story, [
    ("$30 / month", "Modal Starter credits, no card, 10 GPU concurrency"),
    ("~80 GPU-h / month", "Lightning AI free tier, interruptible T4/A10"),
    ("$1.76", "GPU cost per 60s film on interruptible RTX 4090 (Vast.ai, median)"),
    ("180 GPU-h / week", "Current Kaggle fleet ceiling (6 accounts x 30 h)"),
])

# ---- Chapter 2 ----
h1(story, "Chapter 2 - Method: What Verified Means Here")
P(story, "This research was compiled on September 8, 2026, using a battery of fifteen targeted web "
 "searches whose full result digests are stored in the project's research/ directory, followed by "
 "cross-reading the providers' own pricing and signup pages plus independent 2026 sources. A claim "
 "entered the verified table only when it was confirmed either by the provider's own domain or by "
 "at least two independent 2026 publications. Where sources disagreed - for example, older posts "
 "cite 15 free Lightning credits while the current official page promises up to 30 credits "
 "equivalent to roughly 80 GPU-hours on interruptible machines - the official page was preferred "
 "and the discrepancy is noted in the text.")
P(story, "Every candidate was also judged against four operator constraints that marketing pages "
 "never mention. First, no-credit-card signup, because the operator is in Nigeria and international "
 "card friction is real. Second, CUDA compatibility, because the entire render stack - ComfyUI, the "
 "MiniMax-H3 open weights, SDXL keyframes, Wav2Lip - is CUDA-bound. Third, headless automation: a "
 "worker the fleet brain cannot start, feed, and harvest through an SDK or API is a toy, not a "
 "fleet member. Fourth, recurring capacity: one-shot trial credits do not scale, so they were "
 "classified as paid-upgrade options rather than fleet members.")
P(story, "One limitation is stated up front: account creation itself requires the owner's email or "
 "phone, so no provider in this report has been load-tested with the actual H3 stack from this "
 "workspace. What is verified is each offer's existence, size, terms and automation surface. The "
 "first live test on each platform is queued as part of the build plan in Chapter 7, and nothing "
 "will be reported as delivered until it renders a real scene end to end.")

# ---- Chapter 3 ----
h1(story, "Chapter 3 - Baseline: The Kaggle Fleet Today")
P(story, "The fleet's job is to turn a studio script into finished scenes. Each claimed job draws "
 "character sheets and a keyframe per scene with SDXL, renders the scene with the MiniMax-H3 "
 "image-to-video pipeline anchored on that keyframe, optionally voices and lip-syncs dialogue with "
 "edge-tts and Wav2Lip, then uploads the result to Supabase Storage and writes it back to the "
 "queue. The measured cost of that pipeline on Kaggle's T4/P100 class is approximately 2.3 GPU-hours "
 "for a five-second scene at 960x544 and 24 fps. A sixty-second film assembled from eight such "
 "scenes therefore costs roughly 18 GPU-hours, and each new GPU session spends another 20-25 "
 "minutes downloading the 35 GB model stack before its first frame - a tax the dataset-cache fix "
 "now in progress will largely erase.")
P(story, "Kaggle grants each account about 30 GPU-hours per week, which makes one account worth "
 "roughly 1.7 sixty-second films per week at best. Six accounts therefore top out near 180 "
 "GPU-hours per week - around ten films in theory, six to eight once setup overhead and idle "
 "windows are priced in. This week demonstrated the other property of that model: all six tanks "
 "drained at once, the weekly quota wall stopped every push attempt with the same error text, and "
 "the fleet sat grounded. The quota-recovery orchestrator now running checks every thirty minutes "
 "and will re-push the campaign kernel and the lip-sync site workers the moment the weekly reset "
 "lands on Friday night into Saturday 00:00 UTC.")
P(story, "The baseline matters because it sets the exchange rate for every recommendation in this "
 "report: one added Kaggle-class account is worth about 130 GPU-hours a month, one Modal Starter "
 "account is worth about 50, one Lightning free account about 80 on interruptible machines. None "
 "of them change the per-film cost; they divide the same 18 GPU-hours across more parallel tanks.")

# ---- Chapter 4 ----
h1(story, "Chapter 4 - Verified Candidates for the Fleet")
mk_table(story,
    ["Provider", "Free offer (no card)", "GPU class", "Automation path", "Fleet fit"],
    [
        ["<b>Modal</b>", "$30 compute credits monthly; $0 base plan; 10 GPU concurrency; signup with GitHub/Google",
         "T4, A10, A100, H100 (per-second billing)", "First-class Python SDK; GPU functions in ~10 lines; secrets support", "Excellent - primary next driver"],
        ["<b>Lightning AI</b>", "1 free Studio; up to 30 free credits, about 80 GPU-h on interruptible machines",
         "T4 / A10 interruptible", "lightning_sdk can create, start and run Studios programmatically", "Good - second driver, needs preemption handling"],
        ["<b>Hugging Face</b>", "Community GPU grants (application); small free ZeroGPU quota",
         "A100 slices (ZeroGPU) when granted", "Spaces + gradio_client API; grant application form", "Upside - apply now, not a plan of record"],
        ["<b>Azure for Students</b>", "$100 credit per 12 months, no card, renewable yearly with student verification",
         "NC-series T4 VMs", "Full ARM/Azure SDK; VM runs the existing worker script", "Conditional - only if owner can verify student status"],
    ],
    [0.13, 0.30, 0.16, 0.24, 0.17],
    "Table 1: Verified free-tier candidates, September 2026. Sources: provider pages plus independent 2026 pricing trackers.")

h2(story, "4.1 Modal - the best single addition", toc=True)
P(story, "Modal's signup page advertises exactly what the fleet needs: thirty dollars of free "
 "monthly compute on a Starter plan with a zero-dollar base fee, reached with a GitHub or Google "
 "login rather than a credit card. Independent 2026 pricing trackers confirm the plan ships three "
 "workspace seats, one hundred container concurrency and, critically, ten GPU concurrency - a "
 "single free account can run ten render workers in parallel. At Modal's published T4 rate of "
 "0.59 dollars per hour, the monthly credit is worth roughly 50 T4-hours, or two to three "
 "sixty-second films. Billing is per second, so idle setup time is not charged while it downloads.")
P(story, "The decisive advantage is automation quality. A Modal worker is a Python function "
 "decorated with a GPU request; the SDK handles images, queues, secrets and autoscaling. The "
 "existing site-worker logic - claim a row with SKIP LOCKED, render, upload, write back - ports "
 "almost line for line, and the fleet brain gains a second driver next to its Kaggle pusher. "
 "Modal also runs an academic credits program granting up to 10,000 dollars, worth revisiting if "
 "DeYoung ever publishes its pipeline work.")
h2(story, "4.2 Lightning AI - big interruptible allowance", toc=True)
P(story, "Lightning's official pricing page states that a free account runs one Studio and receives "
 "up to 30 free credits, which it equates to roughly 80 GPU-hours per month on interruptible "
 "machines - T4 and A10 hardware documented in the free tier, with interruptible T4 rates around "
 "0.19-0.24 dollars per hour. No card is required at signup. The lightning_sdk can create a "
 "Studio, start it, and execute scripts inside it, which is enough for the fleet brain to treat a "
 "Studio as another worker slot.")
P(story, "The word interruptible carries the operational catch: Lightning can preempt these "
 "machines when capacity tightens. DeYoung's render jobs are already atomic per scene - a killed "
 "scene is marked failed and can be requeued - so the change required is a small requeue rule in "
 "the worker rather than a redesign. With that in place, 80 free GPU-hours a month is the second "
 "largest verified free allowance after Kaggle itself.")
h2(story, "4.3 Hugging Face - grants and ZeroGPU", toc=True)
P(story, "Hugging Face's free individual quota on ZeroGPU is too small to render video, and the "
 "Inference Providers' credits evaporate on a single generation, so neither is a fleet member. "
 "The real opportunity is the community GPU grant program: Hugging Face funds compute for "
 "projects that give back to its ecosystem, and applications are free. A public DeYoung Space "
 "showcasing films rendered with open models - MiniMax-H3, SDXL, Wav2Lip - is a credible "
 "application with visible public output. Treat the grant as upside with a real form to fill, not "
 "as capacity the plan depends on.")
h2(story, "4.4 Azure for Students - conditional", toc=True)
P(story, "Microsoft's Azure for Students program grants 100 dollars of credit per year with no "
 "credit card, renewable annually while the holder can verify active student status. At NC-series "
 "T4 VM rates of roughly 0.5-0.9 dollars per hour, one year of credit is 110-200 GPU-hours. The "
 "gate is verification: the owner would need a school email or document. If that exists, a small "
 "Azure VM running the existing worker script under systemd is a straightforward, fully "
 "automatable addition; if not, the program is simply skipped - no workaround or card tricks are "
 "recommended.")
chart_block(story, "/home/z/my-project/research/chart_capacity.png",
    "Figure 1: Verified free GPU allowance per month, per added account. Kaggle bar marks the existing fleet baseline.")

# ---- Chapter 5 ----
h1(story, "Chapter 5 - Excluded Platforms, and Why, Honestly")
P(story, "Half of this research is negative results, and they are recorded with the same care as "
 "the positives so that no week is wasted re-evaluating a dead end. Google Colab's free T4 is "
 "real but dynamically capped with cooldowns that vary per account, and Colab has no official "
 "automation interface - the browser notebook is the product. A worker the fleet brain cannot "
 "start, feed and harvest programmatically fails the fourth constraint in Chapter 2 regardless of "
 "how generous its hardware looks.")
mk_table(story,
    ["Platform", "Verdict", "Verified reason"],
    [
        ["Google Colab (free)", "Excluded", "Dynamic usage caps and cooldowns; no official headless automation API; browser-first product"],
        ["AWS SageMaker Studio Lab", "Excluded", "AWS published a migration guide off the product (Oct 2025); no evidence of open 2026 enrollment"],
        ["Intel Tiber AI Cloud", "Excluded", "Free JupyterLab exists, but Intel Gaudi / Max accelerators are not CUDA; the render stack cannot run on them"],
        ["Paperspace (DigitalOcean) free GPU", "Marginal", "Free plan still listed, but older GPUs, session caps, and no reliable headless automation on free tier"],
        ["Oracle Cloud Always Free", "Excluded", "ARM Ampere CPUs only - no GPU tier exists in the always-free catalog"],
        ["GCP / AWS trial credits", "Excluded for now", "Card required at signup (Nigeria friction); one-shot credits are not recurring capacity"],
        ["Baseten / Beam / Cerebrium / fal / Novita", "Not fleet material", "Small one-shot trial credits; reappear in Chapter 8 as paid burst options"],
    ],
    [0.24, 0.14, 0.62],
    "Table 2: Platforms evaluated and excluded, with the specific reason.")
P(story, "Two exclusions deserve emphasis because their landing pages are genuinely attractive. "
 "Intel Tiber's free tier is real, but accelerators without CUDA cannot run ComfyUI, and porting "
 "the stack is a research project, not an ops task. Oracle's always-free tier is legendary for "
 "CPUs, yet contains no GPU at any price of patience. Both were checked rather than assumed, "
 "because the owner asked for real answers, and real answers sometimes close doors.")

# ---- Chapter 6 ----
h1(story, "Chapter 6 - Capacity Math for Real Users")
P(story, "Fleet size only matters through its effect on the two scenarios the owner cares about: "
 "how many sixty-second films the platform can deliver per week, and how long two simultaneous "
 "users wait for their films. Both follow from one measured number - 18 GPU-hours per sixty-second "
 "film on T4-class hardware - and one structural fact: a Kaggle account is a 30-hour weekly tank, "
 "not an always-on machine. The tank model means the free fleet's capacity is bursty: it drains "
 "through the week and refills at the Friday-night reset.")
mk_table(story,
    ["Effective T4-class workers", "Weekly GPU-hours", "60s films per week", "Both users' films done in"],
    [
        ["3", "90", "about 5", "about 12 hours"],
        ["6 (today)", "180", "about 10", "about 6 hours"],
        ["10", "300", "about 17", "about 3.6 hours"],
        ["20", "600", "about 34", "about 1.8 hours"],
    ],
    [0.28, 0.22, 0.24, 0.26],
    "Table 3: Capacity and two-user wall time by fleet size, assuming quota is available and 18 GPU-hours per film.",
    align_center_cols=(0, 1, 2, 3))
P(story, "The table's last column is the direct answer to the owner's question. Two users "
 "submitting sixty-second films at the same moment split the fleet between them; with today's six "
 "workers both films finish in roughly six hours of wall time - not 24 - provided the weekly tanks "
 "have water. The catch is the tank: six accounts hold 180 hours per week in total, so the fleet "
 "can only sustain about ten films a week before the wall returns. Adding Modal's 50 monthly "
 "hours and Lightning's 80 lifts sustainable weekly capacity by roughly a third, and every "
 "genuinely new account shifts the whole curve.")
chart_block(story, "/home/z/my-project/research/chart_walltime.png",
    "Figure 2: Wall time until both users' 60-second films are delivered, by effective fleet size (36 film-hours split across N workers).")
P(story, "Figure 2 makes the diminishing returns visible: the jump from three to six workers "
 "halves the wait, while the jump from ten to twenty - which requires either many Kaggle accounts "
 "with their terms-of-service exposure, or the first paid dollars - saves another 1.8 hours. "
 "Parallelism divides wall time; only cheaper per-film cost changes the economics. That is why "
 "the plan in the next chapter spends effort on automation-friendly free platforms first and "
 "reserved paid capacity at the moment the first revenue arrives.")

# ---- Chapter 7 ----
h1(story, "Chapter 7 - Recommended Build Plan")
h2(story, "Phase 1 - this week, zero dollars", toc=True)
P(story, "The owner creates two accounts, which take about ten minutes each and require no card: "
 "Modal (GitHub login) and Lightning AI (email). Each account's API token goes into the encrypted "
 "vault - the same rebuild-proof mechanism that now also carries the fleet database secret - and "
 "the fleet brain gains two drivers. The Modal driver lands first because its SDK is the cleanest: "
 "a GPU function that claims from the same production queue the Kaggle kernels use. The Lightning "
 "driver follows with one addition: automatic requeue of any scene a preemption kills mid-flight. "
 "Kaggle stays at its current six accounts; growing it further multiplies terms-of-service "
 "exposure for diminishing returns.")
h2(story, "Phase 2 - parallel, still zero dollars", toc=True)
P(story, "Three workstreams run without waiting on anything. First, the Hugging Face community "
 "grant application, backed by the public premiere wall as evidence of open-model creative output. "
 "Second, the model-weights dataset snapshotter: a CPU-only Kaggle job packages the 35 GB stack "
 "into a private Kaggle dataset so every future GPU session mounts instead of downloads, cutting "
 "per-session setup from 20-25 minutes to about 3 and recovering roughly 15 percent of weekly "
 "quota. Third, the owner decides on Azure for Students if - and only if - student verification is "
 "honestly available.")
h2(story, "Phase 3 - first revenue", toc=True)
P(story, "When the first paying users arrive, the fleet adds an interruptible RTX 4090 pool on "
 "Vast.ai. The same ComfyUI-plus-H3 container that runs on Kaggle runs unchanged on a 4090, about "
 "3.5 to 4 times faster per scene, at a median of 0.39 dollars per hour. A sixty-second film then "
 "costs under two dollars in GPU time and finishes in roughly four to five hours on a single "
 "card, or under an hour when burst across eight. This is the step that converts user money into "
 "user-perceived speed at the best exchange rate found anywhere in this research.")

# ---- Chapter 8 ----
h1(story, "Chapter 8 - The Paid Upgrade Path: First-Revenue Math")
mk_table(story,
    ["Provider", "GPU", "Rate (2026)", "GPU cost per 60s film", "Role"],
    [
        ["Vast.ai (interruptible)", "RTX 4090 24 GB", "$0.13-0.39/h live median", "about $1.76 at median (4.5 h x $0.39)", "Bulk overflow once users pay"],
        ["RunPod (on-demand)", "RTX 4090 24 GB", "$0.74/h", "about $3.33 (4.5 h x $0.74)", "Reliable on-demand when interruptible is dry"],
        ["Modal (beyond credits)", "T4", "$0.59/h per-second", "about $10.6 on T4 (18 h) - prefer faster GPUs", "Burst CPU + small GPU jobs"],
        ["H100 class (RunPod/Modal)", "H100 80 GB", "$3.95-4.55/h effective", "about $9-14 (2-3 h)", "Premium tier later, not now"],
    ],
    [0.22, 0.15, 0.20, 0.25, 0.18],
    "Table 4: Verified paid rates and per-film GPU cost. 4090 assumed 3.5-4x a T4 on this workload; H100 about 6-8x.")
P(story, "The margin story is straightforward. At the owner's planned price point of 5,000-10,000 "
 "naira per film - three to seven dollars - a Vast-rendered film's median GPU cost of 1.76 dollars "
 "leaves roughly 45-70 percent of revenue for everything that is not GPU. Three paying users "
 "therefore do not merely fund an upgrade; they fund the entire paid tier before the platform has "
 "to think about efficiency work. The same three users on free-tier-only capacity would each wait "
 "in a weekly quota lottery instead - which is precisely the experience the owner refuses to sell.")
P(story, "The upgrade also rewrites the user-facing promise. Free-tier delivery is measured in "
 "days and depends on which day of the quota week it is; a single 4090 delivers a sixty-second "
 "film in four to five hours regardless of the calendar, and an eight-way paid burst delivers in "
 "30-60 minutes. The recommendation is to keep free-tier capacity as the default lane and "
 "introduce the paid lane the week revenue begins, using per-film GPU cost as the floor for "
 "pricing decisions.")
callout(story, [
    ("$1.76", "Median GPU cost per 60s film (Vast 4090 interruptible)"),
    ("45-70%", "GPU margin at the planned 3-7 dollar price point"),
    ("4-5 h", "60s film wall time on one paid 4090"),
])

# ---- Chapter 9 ----
h1(story, "Chapter 9 - Risks, Limits and Honest Unknowns")
P(story, "The fleet's largest structural risk is already inside it: Kaggle's terms state one "
 "account per person, and the platform's competition pages repeat that rule verbatim. Six accounts "
 "operated carefully have worked for months, but every additional account increases exposure to a "
 "policy the operator does not control. The mitigation is exactly this report's strategy - "
 "diversify into platforms designed for programmatic use, and stop growing the Kaggle multiplier "
 "beyond a modest number. The owner should weigh new Kaggle accounts with that trade-off in view "
 "rather than treat them as free capacity.")
P(story, "Free tiers are best-effort by nature. Modal's monthly credit policy and Lightning's "
 "interruptible quotas are published today and can change; nothing in this report is an SLA, and "
 "every figure carries its retrieval date, September 8, 2026. Lightning preemption will kill a "
 "scene occasionally; the planned requeue rule converts that from data loss into a delay. Modal "
 "credits not spent within the month do not roll over, so the driver should keep Modal workers "
 "busy on real queue depth rather than parked idle.")
P(story, "Finally, the honest unknowns. The H3 stack has never run on Modal or Lightning "
 "hardware from this workspace, because account creation requires the owner's identity; VRAM fit, "
 "driver versions and cold-start times will be confirmed by the first live test, and the T4-class "
 "evidence from Kaggle makes failure unlikely but not impossible. No claim in this report about "
 "those platforms should be treated as battle-tested until a DeYoung scene renders there end to "
 "end - the same standard every prior fleet claim was held to.")

# ---- Chapter 10 ----
h1(story, "Chapter 10 - Immediate Next Actions")
P(story, "For the owner, the critical path is three small actions. Create a Modal account with the "
 "GitHub login and send the API token; create a Lightning AI account and send its token; decide "
 "whether Azure for Students is honestly available through school verification. Optionally, and "
 "with the terms-of-service trade-off from Chapter 9 in mind, one or two additional Kaggle "
 "accounts can extend the weekly tank modestly. Each token goes into the encrypted vault on "
 "arrival, so no future sandbox rebuild can lose it.")
P(story, "For the fleet AI, the queue is: wire the Modal driver and prove it with one real scene "
 "rendered end to end; add the Lightning driver with preemption requeue and do the same; land the "
 "35 GB dataset snapshotter so every future session boots in about three minutes; keep the "
 "quota-recovery orchestrator watching the Friday-night reset so the campaign film and the "
 "lip-sync proof render resume automatically. Every step will be self-tested against the live "
 "queue and reported with evidence, in keeping with the standing rule that nothing is done until "
 "it is demonstrated done.")
story.append(Spacer(1, 16))
h2(story, "Sources (all retrieved September 8, 2026)")
for s in [
    "modal.com/pricing and modal.com/signup - Starter plan, $30 monthly credits, GPU concurrency, T4 rate.",
    "beam.cloud and usagepricing.com 2026 pricing explainers - independent confirmation of Modal plan terms.",
    "lightning.ai/pricing - free Studio, 30 credits, about 80 GPU-hours on interruptible machines; T4/A10 free hardware.",
    "thundercompute.com, gmicloud.ai 2026 free-GPU roundups - cross-checks for Lightning, Modal, Azure terms.",
    "kaggle.com competition rules and community answers - one-account-per-person policy text.",
    "docs.aws.amazon.com - SageMaker Studio Lab migration guidance (October 2025).",
    "cloud.intel.com and Intel Tiber AI Cloud developer pages - free tier hardware (Gaudi / Max, non-CUDA).",
    "digitalocean.com paperspace pricing - free GPU plan listing and limits.",
    "vast.ai live pricing pages - RTX 4090 interruptible rates, $0.13-0.39/h median band.",
    "runpod.io pricing - RTX 4090 $0.74/h on-demand, serverless equivalents, H100 rates.",
    "azure.microsoft.com - Azure for Students, $100/12 months, no credit card, renewal terms.",
]:
    story.append(Paragraph(s, bib_st))

doc = TocDocTemplate(OUT, pagesize=A4,
                     leftMargin=MARGIN, rightMargin=MARGIN,
                     topMargin=MARGIN, bottomMargin=MARGIN,
                     title=TITLE, author="Z.ai", creator="Z.ai",
                     subject="DeYoung fleet GPU expansion research 2026")
doc.multiBuild(story, onFirstPage=on_page, onLaterPages=on_page)
print("body built:", OUT)
