"""Generate schemas/*.schema.json (draft 2020-12) - run once, output is committed."""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "schemas"
OUT.mkdir(exist_ok=True)


def write(name: str, schema: dict) -> None:
    schema = {"$schema": "https://json-schema.org/draft/2020-12/schema",
              "$id": f"https://pati.local/schemas/{name}.schema.json", **schema}
    (OUT / f"{name}.schema.json").write_text(json.dumps(schema, indent=2))


S = {
    "capability": {
        "type": "object",
        "required": ["capability_id", "category", "description", "risky", "min_autonomy_level"],
        "properties": {
            "capability_id": {"type": "string", "pattern": "^[A-Za-z0-9_]+$"},
            "category": {"type": "string"},
            "description": {"type": "string", "minLength": 10},
            "risky": {"type": "boolean"},
            "min_autonomy_level": {"type": "integer", "minimum": 0, "maximum": 6},
            "worker_types": {"type": "array", "items": {"type": "string"}},
        },
    },
    "model": {
        "type": "object",
        "required": ["model_id", "name", "provider", "modality", "license", "cost",
                     "free_status", "status"],
        "properties": {
            "model_id": {"type": "string"},
            "name": {"type": "string"},
            "organization": {"type": "string"},
            "provider": {"type": "string"},
            "version": {"type": "string"},
            "modality": {"type": "string"},
            "capabilities": {"type": "array", "items": {"type": "string"}},
            "license": {"type": "string"},
            "license_url": {"type": ["string", "null"]},
            "source_url": {"type": ["string", "null"]},
            "repository_url": {"type": ["string", "null"]},
            "model_url": {"type": ["string", "null"]},
            "hardware_requirements": {"type": "string"},
            "RAM_requirement": {"type": "string"},
            "VRAM_requirement": {"type": "string"},
            "quantization_options": {"type": "array", "items": {"type": "string"}},
            "context_length": {"type": "integer"},
            "languages": {"type": "array", "items": {"type": "string"}},
            "input_types": {"type": "array", "items": {"type": "string"}},
            "output_types": {"type": "array", "items": {"type": "string"}},
            "latency_estimate": {"type": "string"},
            "quality_score": {"type": "number"},
            "speed_score": {"type": "number"},
            "cost": {"type": "number", "maximum": 0,
                     "description": "FREE_ONLY: any positive cost is rejected"},
            "free_status": {"enum": ["FREE_FOREVER", "FREE_WITH_LIMITS",
                                     "OPEN_SOURCE_SELF_HOSTED"]},
            "availability": {"type": "string"},
            "worker_requirements": {"type": "array", "items": {"type": "string"}},
            "startup_time": {"type": "string"},
            "cold_start_time": {"type": "string"},
            "max_context": {"type": "integer"},
            "tool_calling_support": {"type": "boolean"},
            "structured_output_support": {"type": "boolean"},
            "vision_support": {"type": "boolean"},
            "reasoning_support": {"type": "boolean"},
            "commercial_use": {"type": "string"},
            "license_restrictions": {"type": "string"},
            "known_limitations": {"type": "string"},
            "benchmark_results": {"type": "array"},
            "last_verified": {"type": "string"},
            "status": {"type": "string"},
        },
    },
    "tool": {
        "type": "object",
        "required": ["tool_id", "name", "description", "capabilities", "license",
                     "free_status", "status"],
        "properties": {
            "tool_id": {"type": "string"},
            "name": {"type": "string"},
            "description": {"type": "string"},
            "category": {"type": "string"},
            "capabilities": {"type": "array", "items": {"type": "string"}},
            "version": {"type": "string"},
            "source": {"type": "string"},
            "repository": {"type": ["string", "null"]},
            "documentation": {"type": ["string", "null"]},
            "license": {"type": "string"},
            "install_method": {"type": "string"},
            "runtime": {"type": "string"},
            "dependencies": {"type": "array", "items": {"type": "string"}},
            "hardware_requirements": {"type": "string"},
            "network_requirements": {"type": "string"},
            "input_schema": {"type": "object"},
            "output_schema": {"type": "object"},
            "health_check": {"type": ["string", "object"]},
            "benchmark_command": {"type": ["string", "null"]},
            "security_profile": {"type": "string"},
            "sandbox_required": {"type": "boolean"},
            "worker_type": {"type": "string"},
            "startup_command": {"type": ["string", "null"]},
            "shutdown_command": {"type": ["string", "null"]},
            "status": {"type": "string"},
            "last_verified": {"type": "string"},
            "commercial_use": {"type": "boolean"},
            "free_status": {"type": "string"},
            "fallback_tools": {"type": "array", "items": {"type": "string"}},
            "adapter": {"type": "string"},
        },
    },
    "worker": {
        "type": "object",
        "required": ["id", "name", "type", "capabilities", "status"],
        "properties": {
            "id": {"type": "string"},
            "name": {"type": "string"},
            "type": {"enum": ["LOCAL_WORKER", "KAGGLE_WORKER", "CONTAINER_WORKER",
                              "BATCH_WORKER", "REMOTE_FREE_WORKER", "OPTIONAL_CLOUD_WORKER",
                              "BROWSER_WORKER", "CPU_WORKER", "GPU_WORKER", "VIDEO_WORKER",
                              "AUDIO_WORKER", "IMAGE_WORKER", "CODING_WORKER",
                              "RESEARCH_WORKER", "DEPLOYMENT_WORKER"]},
            "capabilities": {"type": "array", "items": {"type": "string"}},
            "status": {"enum": ["online", "offline"]},
            "health": {"enum": ["healthy", "degraded"]},
            "resources": {"type": "object"},
            "machine": {"type": "object"},
            "last_heartbeat": {"type": ["number", "null"]},
            "failure_count": {"type": "integer", "minimum": 0},
        },
    },
    "job": {
        "type": "object",
        "required": ["job_id", "task_id", "stage_id", "op", "capability", "params"],
        "properties": {
            "job_id": {"type": "string"},
            "task_id": {"type": "string"},
            "stage_id": {"type": "string"},
            "stage_name": {"type": "string"},
            "op": {"type": "string"},
            "tool": {"type": ["string", "null"]},
            "capability": {"type": "string"},
            "params": {"type": "object"},
            "deadline_at": {"type": "number"},
            "trace_id": {"type": "string"},
        },
    },
    "task": {
        "type": "object",
        "required": ["id", "objective", "type", "status", "created_at"],
        "properties": {
            "id": {"type": "string"},
            "tenant_id": {"type": "string"},
            "user_id": {"type": ["string", "null"]},
            "parent_task_id": {"type": ["string", "null"]},
            "title": {"type": ["string", "null"]},
            "objective": {"type": "string"},
            "type": {"type": "string"},
            "capability": {"type": ["string", "null"]},
            "input": {"type": ["string", "null"]},
            "constraints": {"type": ["string", "object", "null"]},
            "policy": {"type": ["string", "object", "null"]},
            "plan": {"type": ["string", "object", "null"]},
            "status": {"enum": ["QUEUED", "PLANNING", "ROUTING", "WAITING_FOR_RESOURCE",
                                "RUNNING", "PAUSED", "VALIDATING", "COMPLETED", "FAILED",
                                "CANCELLED", "QUARANTINED"]},
            "progress": {"type": "number"},
            "result": {"type": ["string", "object", "null"]},
            "error": {"type": ["string", "null"]},
            "trace_id": {"type": ["string", "null"]},
            "retry_count": {"type": "integer"},
            "cost": {"type": "number", "maximum": 0},
            "created_at": {"type": "number"},
            "started_at": {"type": ["number", "null"]},
            "completed_at": {"type": ["number", "null"]},
            "stages": {"type": "array", "items": {"type": "object"}},
            "artifact_ids": {"type": "array", "items": {"type": "string"}},
        },
    },
    "artifact": {
        "type": "object",
        "required": ["id", "name", "type", "size", "checksum", "storage"],
        "properties": {
            "id": {"type": "string"},
            "task_id": {"type": ["string", "null"]},
            "stage_id": {"type": ["string", "null"]},
            "worker_id": {"type": ["string", "null"]},
            "name": {"type": "string"},
            "type": {"type": "string"},
            "mime_type": {"type": ["string", "null"]},
            "location": {"type": ["string", "null"]},
            "storage": {"enum": ["control_plane", "local_reference"]},
            "size": {"type": "integer", "minimum": 0},
            "checksum": {"type": "string"},
            "retention": {"type": "string"},
            "visibility": {"type": "string"},
            "provenance": {"type": "object"},
            "metadata": {"type": "object"},
            "created_at": {"type": "number"},
        },
    },
    "provider": {
        "type": "object",
        "required": ["provider_id", "kind", "free_status"],
        "properties": {
            "provider_id": {"type": "string"},
            "kind": {"enum": ["compute", "model", "storage", "api", "connector"]},
            "free_status": {"type": "string"},
            "cost": {"type": "number", "maximum": 0},
            "license": {"type": "string"},
            "last_verified": {"type": "string"},
        },
    },
    "policy": {
        "type": "object",
        "required": ["key"],
        "properties": {
            "key": {"type": "string"},
            "value": {},
            "FREE_ONLY": {"type": "boolean", "const": True},
            "MAX_SPEND": {"type": "number", "const": 0},
        },
    },
    "tenant": {
        "type": "object",
        "required": ["id", "name"],
        "properties": {"id": {"type": "string"}, "name": {"type": "string"},
                       "created_at": {"type": "number"}},
    },
    "user": {
        "type": "object",
        "required": ["id", "tenant_id", "name", "role"],
        "properties": {"id": {"type": "string"}, "tenant_id": {"type": "string"},
                       "name": {"type": "string"},
                       "role": {"enum": ["admin", "member", "service"]}},
    },
    "agent": {
        "type": "object",
        "required": ["agent_id", "kind"],
        "properties": {"agent_id": {"type": "string"},
                       "kind": {"enum": ["PERSONAL_AI_CLIENT", "CLI_CLIENT",
                                         "API_CLIENT", "MCP_CLIENT"]},
                       "adapter": {"type": "string"}},
    },
    "adapter": {
        "type": "object",
        "required": ["adapter_id", "target", "kind"],
        "properties": {"adapter_id": {"type": "string"}, "target": {"type": "string"},
                       "kind": {"enum": ["model", "tool", "connector", "worker", "personal_ai"]},
                       "config": {"type": "object"},
                       "health_check": {"type": ["string", "object"]}},
    },
    "benchmark": {
        "type": "object",
        "required": ["id", "target_kind", "target_id", "metrics"],
        "properties": {"id": {"type": "string"},
                       "target_kind": {"enum": ["model", "tool", "worker"]},
                       "target_id": {"type": "string"},
                       "metrics": {"type": "object"},
                       "created_at": {"type": "number"}},
    },
    "health": {
        "type": "object",
        "required": ["status", "service", "version"],
        "properties": {"status": {"const": "ok"}, "service": {"type": "string"},
                       "version": {"type": "string"},
                       "free_only": {"type": "boolean", "const": True},
                       "max_spend": {"const": 0}},
    },
}

for name, schema in S.items():
    write(name, schema)
print(f"wrote {len(S)} schemas to {OUT}")
